## Tarea numpy Simon Londono Aguirre - 1001370696

In [ ]:
import numpy as np

### Punto 1
Dado 2 vectores (arreglos de Numpy unidimensionales) *x* y *y*, calcule la siguiente matriz, conocida como matriz de Cauchy:

$$
C_{ij} = \frac{1}{x_{i}-y_{y}}
$$

In [10]:
def cauchy(x, y):

    d_x = x.reshape(-1, 1) - y.reshape(1, -1)
    d_y = 1.0 / d_x
    
    return d_y

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

cauchy = cauchy(x, y)
print(cauchy)


[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


### Punto 2
Haga una función que genere una matriz con números aleatorios de un tamaño *n* * *m*, donde *n* y *m* son los argumentos de la función. La función debe retornar la matriz generada, una segunda matriz que sea el resultado de restarle al valor de cada elemento la media de la fila correspondiente, y una tercera matriz que sea el resultado de restarle al valor de cada elemento de la primera matriz la media de la columna correspondiente.

In [12]:
def generate_random_matrix(n, m):

    matrix = np.random.rand(n, m)
    row_means = np.mean(matrix, axis=1).reshape(-1, 1)
    matrix_row_means = matrix - row_means
    col_means = np.mean(matrix, axis=0).reshape(1, -1)
    matrix_col_means = matrix - col_means
    
    return matrix, matrix_row_means, matrix_col_means

n = 3
m = 4
random_matrix, matrix_row_means, matrix_col_means = generate_random_matrix(n, m)

print("Matriz 1:")
print(random_matrix)

print("\Matriz 2:")
print(matrix_row_means)

print("\nMatriz 3:")
print(matrix_col_means)



Matriz 1:
[[0.67308643 0.4774108  0.26090401 0.14651634]
 [0.21743345 0.17202218 0.13861551 0.20791754]
 [0.39638298 0.81809332 0.80896805 0.01431156]]
\Matriz 2:
[[ 0.28360704  0.0879314  -0.12857538 -0.24296306]
 [ 0.03343628 -0.01197499 -0.04538166  0.02392037]
 [-0.113056    0.30865434  0.29952908 -0.49512742]]

Matriz 3:
[[ 0.24411881 -0.01176463 -0.14192518  0.02360119]
 [-0.21153417 -0.31715325 -0.26421368  0.08500239]
 [-0.03258464  0.32891789  0.40613886 -0.10860359]]


### Punto 3
Haga una función que reciba como argumento una matriz cuadrada y retorne la misma matriz pero con los valores de su diagonal principal elevados al cuadrado.

In [14]:
import numpy as np

def diagonal(matrix):

    result_matrix = matrix.copy()
    n = matrix.shape[0]
    result_matrix[np.arange(n), np.arange(n)] **= 2
    
    return result_matrix

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

result = diagonal(matrix)

print("\nMatriz con los valores de la diagonal principal elevados al cuadrado:")
print(result)



Matriz con los valores de la diagonal principal elevados al cuadrado:
[[ 1  2  3]
 [ 4 25  6]
 [ 7  8 81]]


### Punto 4
Haga una función que reciba un arreglo tridimensional de tamaño (4,6,8), y entregue un arreglo bidimensional (6,8) que contenga la suma de los elementos de la dimensión colapsada.

In [17]:
import numpy as np

def collapse_dimension(arr):
    
    collapsed_arr = np.sum(arr, axis=0)
    return collapsed_arr

arr = np.random.randint(0, 10, size=(4, 6, 8))

collapsed_arr = collapse_dimension(arr)


print("Arreglo colapsado de tamaño (6, 8):")
print(collapsed_arr.shape)
print(collapsed_arr)


Arreglo colapsado de tamaño (6, 8):
(6, 8)
[[20 27 27  8 16 19 14 22]
 [18 14 29 23 16 10 21 13]
 [22 26 12 28 17 27 23 19]
 [14 19 18  8 21 19 10 21]
 [21 22 20  8 20 13 18 23]
 [10 19 21  7 20 29 10  4]]
